src/components/nav/NavBar.jsx

I mostly wanted to test the workflow.

Merge into staging

---

src/components/GearOptimizer.jsx
src/components/sections/ar/ARSection.jsx
src/components/sections/ar/ARinput.jsx
src/components/sections/buffs/Buffs.jsx
src/components/sections/buffs/BuffsSection.jsx
src/components/sections/controls/Controls.jsx
src/components/sections/distribution/DamageDistribution.jsx
src/components/sections/distribution/DistributionSection.jsx
src/components/sections/extramodifiers/ExtraModifiers.jsx
src/components/sections/extramodifiers/ExtraModifiersSection.jsx
src/components/sections/extras/ExtrasSection.jsx
src/components/sections/extras/GW2Select.jsx
src/components/sections/forcedslots/ForcedSlots.jsx
src/components/sections/forcedslots/ForcedSlotsSection.jsx
src/components/sections/infusions/Infusions.jsx
src/components/sections/infusions/InfusionsSection.jsx
src/components/sections/priorities/Priorities.jsx
src/components/sections/priorities/PrioritiesSection.jsx
src/components/sections/skills/Skills.jsx
src/components/sections/skills/SkillsSection.jsx
src/components/sections/traits/Traits.jsx
src/components/sections/traits/TraitsSection.jsx

doing this as a pr to avoid possible merge hell

Refactor: split sections into separate files

---

src/components/sections/ar/ARinput.jsx

Fix: Parse AR input

---

src/components/sections/results/ResultDetails.jsx
src/state/gearOptimizerSlice.js
src/state/optimizer/optimizerCore.js
src/state/optimizer/sagas.js

This:
- Simplifies the code handling the generator* function used for calculation (I did change one line in OptimizerCore, which would need a slight change to the old optimizer to sync, but idk if we're gonna keep updating that)
- Cleans up the data logged to the console during calculation (template creation data is all together)
- Clears the result character when you press calculate... unless the calculation is very quick, in which case it's smoother to just replace it

Refactor: calculation/rendering/console logic

---

src/components/gw2/BackAndTrinkets.jsx
src/components/gw2/Weapons.jsx
src/components/nav/NavBar.jsx
src/components/sections/controls/CopyTemplateButton.jsx
src/components/sections/distribution/DamageDistribution.jsx
src/components/sections/forcedslots/ForcedSlots.jsx
src/components/sections/infusions/Infusions.jsx
src/components/sections/results/AppliedModifiers.jsx
src/components/sections/results/OutputDistribution.jsx
src/components/sections/results/OutputInfusions.jsx
src/components/sections/results/ResultDetails.jsx
src/components/sections/results/SpecialDurations.jsx
src/components/sections/traits/Traits.jsx
src/state/optimizer/optimizerCore.js
src/state/optimizer/sagas.js
src/state/slices/skills.js
src/state/slices/traits.js

Kept getting confused by single letter variable names so I tried to rename them all. Don't think I fully understood all the code though so some of these may be misleading/wrong.

Refactor: clarify short variables

---

src/components/sections/traits/Traits.jsx

hide traitlines if none selected

---

src/assets/modifierdata/engineer.yaml
src/assets/presetdata/preset-distribution.yaml
src/assets/presetdata/preset-traits.yaml

This fills out the base traits for Holosmith PBM since that's the one listed on discretize.eu.
I wasn't sure if this would be useful without modeling the corresponding modifiers and effects so feel free to reject this. I thought I'd get the ball rolling with an easy fix then move on to wherever I can be the most useful (suggestions welcome!)

Add Holosmith trait presets for Power Holo

---

src/assets/presetdata/preset-infusions.yaml
src/components/GearOptimizer.jsx
src/components/sections/infusions/Infusions.jsx
src/components/sections/infusions/InfusionsSection.jsx
src/state/slices/infusions.js

This adds presets to the infusions section. They aren't autoselected by templates (I could go either way on this).

Add infusion preset buttons

---

docs/Contributing/Data Format/Templates and Presets.md
package.json
src/assets/presetdata/package.json
src/assets/presetdata/preset-distribution.yaml
src/assets/presetdata/preset-extras.yaml
src/assets/presetdata/preset-traits.yaml
src/assets/presetdata/templates.yaml
src/assets/presetdata/testPresets.js
src/components/GearOptimizer.jsx
src/components/nav/NavAccordion.jsx
src/components/nav/NavBar.jsx
src/components/sections/controls/TemplateHelper.jsx
src/components/sections/distribution/DistributionSection.jsx
src/components/sections/extras/ExtrasSection.jsx
src/components/sections/traits/TraitsSection.jsx
src/state/slices/extras.js
src/state/slices/priorities.js
src/state/slices/skills.js
src/state/slices/traits.js

Implement reformatted preset data

---

yarn.lock

This regenerates yarn.lock, updating subdependencies.

Clean up dependency lockfile

---

jsconfig.json

Apparently vs code wants me to do this?

add exclusions to jsconfig.json

---

src/assets/presetdata/preset-distribution.yaml
src/assets/presetdata/preset-traits.yaml

Writes all the data from the spreadsheet I have been using to keep track of template sources into comments in the template yaml itself.
Updates some templates.

Update and document preset data

---

src/assets/presetdata/preset-distribution.yaml
src/components/sections/controls/TemplateHelper.jsx
src/components/sections/distribution/DistributionSection.jsx
src/state/slices/distribution.js

Removes percentage distributions from presets and just sets them in the reducer, since there's a set formula for them.

Automatic percent distribution

---

.eslintrc.json
src/components/sections/distribution/DamageDistribution.jsx

Tries to make applying a template or changing v2 distributions change the percent distribution slider.

set percent distribution slider

---

src/components/sections/controls/Controls.jsx
src/components/sections/results/ResultDetails.jsx
src/state/controlsSlice.js
src/state/optimizer/sagas.js
src/state/slices/buffs.js
src/state/slices/extraModifiers.js
src/state/slices/extras.js
src/state/slices/infusions.js
src/state/slices/skills.js
src/state/slices/traits.js

Moves applied modifiers from all over the redux state to a key in `control`. Maybe.

Move setModifiers

---

package.json
src/components/nav/NavBar.jsx
src/state/optimizer/sagas.js
src/state/slices/buffs.js
src/state/slices/controlsSlice.js
src/state/slices/distribution.js
src/state/slices/extraModifiers.js
src/state/slices/extras.js
src/state/slices/forcedSlots.js
src/state/slices/infusions.js
src/state/slices/priorities.js
src/state/slices/skills.js
src/state/slices/traits.js
yarn.lock

@gw2princeps, feel free to use any of or none of this.
I haven't done the code to store result characters so they're not massive yet. Should be easy though.

demo backend for sharable state

---

src/components/sections/results/ResultDetails.jsx

Well, this is what I get for disabling eslint rules :P

Fix: Lodash import

---

docs/Contributing/Data Format/Templates and Presets.md
src/assets/modifierdata/index.js
src/assets/presetdata/preset-distribution.yaml
src/assets/presetdata/preset-extras.yaml
src/assets/presetdata/preset-traits.yaml
src/assets/presetdata/templates.yaml
src/assets/presetdata/testPresets.js
src/components/baseComponents/Presets.jsx
src/components/gw2/Attributes.jsx
src/components/nav/NavAccordion.jsx
src/components/nav/NavBar.jsx
src/components/sections/controls/CopyTemplateButton.jsx
src/components/sections/results/ResultDetails.jsx
src/components/sections/results/WeaponSelect.jsx
src/components/sections/skills/SkillsSection.jsx
src/components/sections/traits/TraitsSection.jsx
src/state/optimizer/sagas.js
src/state/slices/controlsSlice.js
src/utils/gw2-data.js

This changes every reference that I could find to a profession or specialization name not to change the case, and changes the cases to Firstuppercase.
I think this will require changes to the character component of the main site... again. Maybe not worth it?

Consistent profession capitalization

---

src/assets/presetdata/preset-infusions.yaml
src/components/sections/infusions/Infusions.jsx
src/components/sections/results/OutputInfusions.jsx
src/components/sections/results/ResultDetails.jsx
src/components/sections/results/ResultTableHeaderRow.jsx
src/state/optimizer/sagas.js
src/utils/gw2-data.js

Store infusions as types instead of ids

---

src/components/sections/results/ResultDetails.jsx
src/components/sections/results/ResultTable.jsx
src/components/sections/results/ResultTableHeaderRow.jsx
src/components/sections/results/TemplateHelper.jsx
src/state/optimizer/optimizerCore.js
src/state/optimizer/sagas.js
src/state/slices/controlsSlice.js
src/state/slices/traits.js

This removes all of the useSelector hooks in the results section that query the form state, replacing them with data stored inside the character object.
This should fix a number of bugs in which changing the form controls would instantly cause changes to the results section even though you didn't click the calculate button. For example, doing a calculation and then changing sigil settings would change what sigils were displayed in the result you were looking at.
part 1 of like 16 in project "make the redux state small enough to fit in a URL"

Store stuff in character

---

src/components/sections/infusions/InfusionHelper.jsx
src/state/slices/infusions.js

Infusion helper PR: change matrix discount slider to number of owned matrix

---

src/components/baseComponents/Presets.jsx
src/components/baseComponents/Profession.jsx
src/components/gw2/Attributes.jsx
src/components/nav/NavAccordion.jsx
src/components/nav/NavBar.jsx

this is sort of silly but oh well

enable core spec templates

---

src/components/sections/infusions/InfusionHelper.jsx

Code is a bit of a meme, I'll be honest. But I'd rather do silly things with the gw2-ui API than do this "properly."

Add back infusion helper colors

---

.github/workflows/test-presets.yml
src/assets/presetdata/testPresets.js

Creates a workflow that checks for invalid JSON in presets.

Test presets json

---

locales/en/translation.json
src/assets/modifierdata/runes.yaml

Add ranger rune

---

docs/Contributing/Data Format/Templates and Presets.md
src/assets/modifierdata/guardian.yaml
src/assets/modifierdata/necromancer.yaml
src/assets/modifierdata/thief.yaml
src/assets/presetdata/preset-traits.yaml
src/components/sections/skills/Skills.jsx
src/state/slices/skills.js
src/state/slices/traits.js

Skill amounts

---

src/components/GearOptimizer.jsx
src/components/baseComponents/AmountInput.jsx
src/components/sections/boss/Boss.jsx
src/components/sections/boss/BossSection.jsx

Feat: Confusion + Torment (UI)

---

src/components/sections/results/ResultTable.jsx
src/components/sections/results/ResultTableHeaderRow.jsx
src/components/sections/results/ResultTableRow.jsx
src/state/slices/controlsSlice.js
src/styles/theme.js

Feat: Save results to compare

---

src/components/baseComponents/HelperIcon.jsx
src/components/sections/controls/Controls.jsx
src/components/sections/results/ResultTableHeaderRow.jsx
src/components/sections/results/ResultTableRow.jsx
src/styles/theme.js

- star is gold now
- helper icon has correct size
- comparison label has correct fontsize

styling: adjustments to past changes

---

src/components/url-state/URLStateExport.jsx
src/components/url-state/URLStateImport.jsx
src/state/optimizer/sagas.js

Implements a call to a url shortener, which is hosted on cloudflare workers
Source for the shortener: https://gist.github.com/gw2princeps/dc88d11e6b2378db35bcb2dd3726c7c6
todo: after this was tested a bit create a subdomain for the discretize.eu domain -> need to talk with metagame
can merge for now to test it

feat: implement url shortener

---

src/components/sections/forcedslots/ForcedSlotsSection.jsx
src/components/sections/priorities/Priorities.jsx
src/state/slices/forcedSlots.js

Feat: buttons to clear or copy forced slots

---

src/components/GearOptimizer.jsx
src/components/baseComponents/EmbossedCard.jsx
src/components/baseComponents/HelperIcon.jsx
src/components/baseComponents/Layout.jsx
src/components/baseComponents/Section.jsx
src/components/nav/NavAccordion.jsx
src/components/nav/NavBar.jsx
src/components/sections/Affixes.jsx
src/components/sections/buffs/Buffs.jsx
src/components/sections/distribution/DamageDistribution.jsx
src/components/sections/extramodifiers/ExtraModifiers.jsx
src/components/sections/extras/GW2Select.jsx
src/components/sections/forcedslots/ForcedSlots.jsx
src/components/sections/infusions/Infusions.jsx
src/components/sections/priorities/Priorities.jsx
src/components/sections/results/AffixesStats.jsx
src/components/sections/results/AppliedModifiers.jsx
src/components/sections/results/Indicators.jsx
src/components/sections/results/OutputDistribution.jsx
src/components/sections/results/OutputInfusions.jsx
src/components/sections/results/ResultTable.jsx
src/components/sections/results/SpecialDurations.jsx
src/components/sections/results/WeaponSelect.jsx
src/components/sections/skills/Skills.jsx
src/components/sections/traits/Traits.jsx

Refactored every occurence of muis withStyles with makeStyles to allow a smooth transition to mui5 in the future.

refactor: replace withStyles with makeStyles

---

gatsby-config.js

I don't know what this does, but I assume it should be updated.

Fix: i18next site url

---

src/assets/modifierdata/necromancer.yaml
src/assets/modifierdata/thief.yaml

This does not need any changes to the schema, right @gw2princeps?

Fix: Missing traitlines

---

src/state/optimizer/optimizerCore.js

This changes the behavior of the "Damage increase/decrease from +5 of attribute" section back to "converted" mode, but does the comparison by calculating new versions of the before-and-after damage with rounding completely disabled in the conversion code.
This allows those results to take things like utility nourishment into account, without any inconsistencies in the result due to rounding. Thus, these results can really be treated as partial derivatives.

Feat: Change effective positive/negative values to no rounding converted

---

src/components/sections/results/TemplateHelper.jsx

This should really, really be in a saga (https://redux-saga.js.org/docs/recipes/#throttling) rather than doing data fetching in a useEffect, but we can move it later.

Feat: Add dps.report import to template helper

---

src/components/baseComponents/ExtrasMultiselect.jsx
src/components/baseComponents/Label.jsx
src/components/sections/extras/ExtraSelection.jsx
src/components/sections/extras/Extras.jsx
src/components/sections/extras/ModalContent.jsx

implements the new way of selecting multiple options for runes/sigils. 
Comments welcome.
TODO:

feat: rework of the multiselect situation

---

src/components/baseComponents/AffixesSelect.jsx

Uses a generic ring for the custom affix select tooltip.

Fix: Custom affix tooltip

---

src/assets/presetdata/preset-extras.yaml
src/assets/presetdata/preset-traits.yaml
src/state/slices/extras.js
src/state/slices/skills.js
src/state/slices/traits.js

Sure hope this doesn't break anything.

Chore: Random state refactor

---

src/assets/modifierdata/testModifiers.ts
updateMappings.js

Obviously I have to fix the typescript in the test scripts, which I'll get to. Making sure the CI passes first, though.

Chore: Lint and check CI workflow

---

src/state/optimizer/optimizerSetup.ts
src/state/slices/forcedSlots.js
src/state/slices/priorities.js

Moves excluded affixes to the priorities slice next to affixes.
Fix imports after merging this!!!!

Move excluded affixes

---

.github/workflows/previews-cf.yml

Chore: Disable CF previews in branches, attempt 2

---

src/assets/modifierdata/elementalist.yaml
src/assets/modifierdata/engineer.yaml
src/assets/modifierdata/guardian.yaml
src/assets/modifierdata/mesmer.yaml
src/assets/modifierdata/necromancer.yaml
src/assets/modifierdata/ranger.yaml
src/assets/modifierdata/revenant.yaml
src/assets/modifierdata/thief.yaml
src/assets/modifierdata/warrior.yaml

sorry for redoing the pull request. i changed the notepad++ settings so the webinterface shows the correct changes,
changes made:
-added wvw modifieres
-some correction on existing traits

Add WvW trait split data

---

build/index.html
index.html
locales/en/translation.json
src/assets/presetdata/preset-affixes.yaml
src/components/sections/priorities/Priorities.jsx
src/state/optimizer/optimizerCore.ts
src/state/optimizer/optimizerSetup.ts
src/state/slices/priorities.js

Feat: Quickness duration

---

src/assets/presetdata/preset-distribution.yaml
src/assets/presetdata/preset-traits.yaml

Update for 2022-07-01 benchmark by Support Hero
https://www.youtube.com/watch?v=2phGf78VtaU
I think I did it right because it predicts the bench log's dps using the preset but please let me know if there's anything I got wrong!

Update Condi Quickbrand distribution and trait presets

---

locales/en/translation.json
src/assets/presetdata/preset-distribution.yaml
src/assets/presetdata/preset-extras.yaml
src/assets/presetdata/templates.yaml

Chore: Update Power Vindicator preset

---

src/components/sections/results/TemplateHelperSections.jsx

Streamlined the props of the character component so that they match everywhere. 
No more weird transmutations in the remark plugin necesary.

feat: support new mdx character format

---

locales/en/translation.json
src/assets/presetdata/credit.yaml
src/assets/presetdata/preset-distribution.yaml
src/assets/presetdata/preset-traits.yaml
src/assets/presetdata/templates.yaml

Received permission from Fallen for the log. Featuring the new unravel rotation

Update Power Weaver (Sword)

---

src/assets/modifierdata/elementalist.yaml

10% as per https://wiki.guildwars2.com/wiki/Woven_Air
I had 20% as a placeholder then forgot to go and confirm it

Decrease Woven Air to actual value

---

src/state/slices/buffs.js
src/state/slices/extraModifiers.js
src/state/slices/extras.js
src/state/slices/infusions.js
src/state/slices/priorities.js
src/state/slices/skills.js
src/state/slices/traits.js

re: https://discord.com/channels/301270513093967872/841624410544930826/1078323248028205086

Chore: Remove unnecessary createSelector optimizations

---

locales/en/translation.json
src/assets/modifierdata/sigils.yaml
src/assets/presetdata/preset-distribution.yaml
src/assets/presetdata/preset-extras.yaml
src/assets/presetdata/preset-traits.yaml
src/assets/presetdata/templates.yaml
src/components/url-state/schema/SchemaDicts.js

New sigil setup! It also changes the rotation so the old geo + torment isn't given as an option (but is kept around for the outdated gs variant)

Update Condi Willbender Sword

---

locales/en/translation.json
src/assets/modifierdata/warrior.yaml
src/assets/presetdata/templates.yaml

https://en-forum.guildwars2.com/topic/130415-game-update-notes-may-2-2023/
Death drop and nomad's advance buffed, smash brawler split between game modes

May 2nd actual changes

---

locales/en/translation.json
src/assets/presetdata/credit.yaml
src/assets/presetdata/preset-affixes.yaml
src/assets/presetdata/preset-distribution.yaml
src/assets/presetdata/preset-traits.yaml
src/assets/presetdata/templates.yaml

90% simple distribution updates for now

May 2 updates: part one

---

locales/en/translation.json
src/assets/presetdata/credit.yaml
src/assets/presetdata/preset-distribution.yaml
src/assets/presetdata/preset-traits.yaml
src/assets/presetdata/templates.yaml

Received permission from Shavy to use their log
Small bonus addition to the pr earlier today

Update Power DH Radiance

---

locales/en/translation.json
src/assets/presetdata/credit.yaml
src/assets/presetdata/preset-distribution.yaml
src/assets/presetdata/preset-traits.yaml
src/assets/presetdata/templates.yaml

Only other build that I'm aware I could update is cfb (still in denial)

May 2 updates continued

---

src/assets/presetdata/preset-distribution.yaml
src/assets/presetdata/preset-extras.yaml

Minor adjustment due to missing the food change for this build

Fix wrong food used in calculating Alacrity Hybrid Tempest

---

src/components/sections/extras/ModalContent.jsx

allows searching all modifierdata of the extras.

feat: search extras by modifier data

---

build/main.jsx
package.json
src/components/sections/results/ResultCharacter.jsx
src/components/sections/results/TemplateHelperSections.jsx
src/pages/build/index.jsx
src/pages/index/main.jsx
src/utils/rdc-styles.css
yarn.lock

Had to update RDC for that, which was apparently multiple years (?) behind the last version. 
RDC was split up into mui globals and just the rdc. Made the necessary changes; didn't see anything break, but please verify as well on the preview branch. 
New features: 
- ResultCharacter displays relic 
- Website copy template buttons insert the relic into the string

Relics display for character

---

src/state/slices/boss.js
src/state/slices/buffs.js
src/state/slices/distribution.js
src/state/slices/extraModifiers.js
src/state/slices/extras.js
src/state/slices/forcedSlots.js
src/state/slices/infusions.js
src/state/slices/priorities.js
src/state/slices/skills.js
src/state/slices/traits.js
src/state/slices/userSettings.js

As per https://redux-toolkit.js.org/api/codemods, this migrates to the "builder callback" notation for redux toolkit's `extraReducers` argument by running `npx @reduxjs/rtk-codemods createSliceBuilder ./src`.

Chore: run Redux Toolkit codemods

---

src/state/optimizer-parallel/utils.ts
src/state/optimizer-parallel/worker/worker.ts

I can't really test this, but I'm assuming it's right.
[no previews]

Chore: Fix relics in heuristics

---

src/assets/testData.js

Enforce additive "all damage" mods until proven otherwise

---

babel-extract-en.config.js
babel-extract.config.js
cleanupLocale.js
extract_context_injection/index.js
generateRustMappings.ts
package.json
pnpm-lock.yaml
src/assets/testData.js
src/utils/require-ts.js
updateMappings.js

Chore: Convert scripts to esm

---

.eslintrc.json
src/state/optimizer-parallel/results.ts
src/state/optimizer-parallel/utils.ts
src/utils/gw2-data.ts
src/utils/usefulFunctions.ts

Enables some more eslint rules.
[no previews]

Chore: Enable "stylistic" `typescript-eslint` rules

---

functions/share/create.ts
src/state/optimizer-parallel/modes/normal.ts
src/state/slices/skills.ts
src/state/slices/traits.ts

Not sure if any of these are the correct fixes but I threw this together as a bandaid if useful/wanted.

Fix minor lint errors

---

src/assets/modifierdata/index.ts
src/assets/modifierdata/yaml.d.ts

Thanks to https://stackoverflow.com/a/51114250.
[no previews]

Fix type implementation for yaml data imports

---

src/assets/presetdata/preset-distribution.yaml
src/assets/presetdata/preset-traits.yaml
src/assets/presetdata/templates.yaml

Updated coefficients on traits and damage distribution

Data: Update Power Holo ECSU as of 2024-04-04

---

locales/en/translation.json
src/assets/presetdata/credit.yaml
src/assets/presetdata/preset-affixes.yaml
src/assets/presetdata/preset-distribution.yaml
src/assets/presetdata/preset-extras.yaml
src/assets/presetdata/preset-traits.yaml
src/assets/presetdata/templates.yaml

Warrior template updates

---

src/components/sections/results/table/ResultTable.jsx
src/components/sections/results/table/ResultTableHeaderRow.jsx
src/components/sections/results/table/ResultTableRow.jsx
src/utils/gw2-data.ts

Fix: Misaligned saved results table

---

src/components/sections/results/TemplateHelper.jsx

Adds support for importing logs from https://gw2wingman.nevermindcreations.de/ in addition to dps.report. Special thanks to Plastique for adding the manually-reparse-the-evtc-please API endpoint used here!

Feat: Add gw2wingman log import support

---

src/assets/presetdata/preset-distribution.yaml
src/state/optimizer/optimizerCore.ts
wasm_module/src/optimizer_core.rs

Fix: Shroud missing wicked corruption base

---

locales/en/translation.json
src/components/sections/results/ConditionDetails.jsx
src/components/sections/results/OtherAttributes.jsx
src/components/sections/results/OutputInfusions.jsx
src/components/sections/results/ResultDetails.jsx
src/state/optimizer-parallel/results.ts
src/state/optimizer-parallel/utils.ts
src/state/optimizer/optimizerCore.ts
src/state/optimizer/optimizerSetup.ts
wasm_module/src/data/attribute.rs
wasm_module/src/optimizer_core.rs

A few things I was working on at the same time (no reason to make separate PRs and run CI a bunch of times).
Resolves #479.

Misc fixes

---

src/assets/modifierdata/mesmer.yaml

Buff on your bar, effects power and condition damage -> probably additive. It would be great if someone confirmed, but at this point, eh.
[skip ci]

Data: Set deadly blades to add

---

locales/en/translation.json
src/assets/modifierdata/engineer.yaml
src/assets/modifierdata/guardian.yaml
src/assets/modifierdata/revenant.yaml
src/assets/modifierdata/warrior.yaml
src/assets/presetdata/preset-traits.yaml
src/pages/index/index.jsx
src/state/optimizer/optimizerSetup.ts
src/state/slices/priorities.ts
src/utils/gw2-data.ts

**outdated builds:**
quickness catalyst
guardian focus builds
guardian spear builds
mesmer scepter builds
necro axe builds
soulbeast lynx builds
revenant spear builds
spellbreaker offhand dagger builds
warrior spear builds

Oct 28 Patch

---

src/state/optimizer-parallel/results.ts
src/state/optimizer-parallel/utils.ts
src/state/optimizer/optimizerCore.ts
src/state/optimizer/optimizerSetup.ts
src/utils/gw2-data.ts

refactor: Improve types for baseAttributes/attributes

---

locales/en/translation.json
src/assets/modifierdata/elementalist.yaml
src/assets/modifierdata/guardian.yaml
src/assets/modifierdata/mesmer.yaml
src/assets/modifierdata/ranger.yaml
src/assets/modifierdata/revenant.yaml
src/assets/presetdata/preset-traits.yaml
src/assets/presetdata/templates.yaml
src/pages/index/index.jsx

https://wiki.guildwars2.com/wiki/Upcoming_changes_and_features/2025-02-11_Balance_Preview
The Nomad's Endurance changes are pretty mystifying.
[draft previews]

Feb 11 Patch

---

package.json
pnpm-lock.yaml

Updates Wrangler to v4, which [that I can tell](https://developers.cloudflare.com/workers/wrangler/migration/update-v3-to-v4/) should require no changes.

chore: Update wrangler

---

package.json
pnpm-lock.yaml
src/assets/modifierdata/metadata.ts
src/components/sections/buffs/Buffs.jsx
src/components/sections/infusions/InfusionHelper.jsx
src/components/sections/infusions/Infusions.tsx
src/components/sections/results/TemplateHelperSections.jsx
src/state/slices/infusions.ts
src/utils/assumedBuffs.ts
src/utils/gw2-data.ts

Implements fractal title buffs, selectable in the infusions/ar section.
I definitely shouldn't have labelled the github issue "good first issue"—without modifications, the code for the boons section doesn't actually support the fractal title buffs, so the simple solution wouldn't have worked.
Resolves #485.

feat: Implement fractal title buffs

---

docs/Contributing/Data Format/Modifiers.md
src/assets/modifierdata/elementalist.yaml
src/assets/modifierdata/metadata.ts
src/assets/testData.js
src/state/optimizer-parallel/utils.ts
src/state/optimizer/optimizerCore.ts
src/state/optimizer/optimizerSetup.ts
src/state/optimizer/types/optimizerTypes.ts
src/utils/gw2-data.ts
wasm_module/src/data/combination.rs
wasm_module/src/data/settings.rs
wasm_module/src/optimizer_core.rs

feat: Implement inferno trait

---

src/assets/presetdata/credit.yaml
src/assets/presetdata/preset-distribution.yaml
src/assets/presetdata/templates.yaml

Using coefficients from Alcatraz and usual late-combat-start workaround

Update Condi Daredevil
