discretize/discretize-gear-optimizer

- src/assets/data/necromancer.yaml
- src/assets/data/preset-distribution.yaml
Target the weak: I didn't notice this patch note rip me
Lingering curse: stats are no longer converted
> Fix: necro trait accuracy and templates

- src/state/optimizer/sagas.js
This puts the list update on a trailing throttle, so up to 4 sequential list updates are all rendered only once.
It also only re-renders the progress percentage if it's actually changed.
> Performance: trailing throttle on rendering list

- src/assets/data/preset-buffs.yaml
- src/assets/data/preset-traits.yaml
This removes warrior buffs from the fractal presets, splits them up, and adds spotter to the power one.
I defaulted all the power builds to the with-spotter template, as building for no spotter and then wasting 100 stat points if you have it is way worse than being slightly under the crit cap, and I assume anyone optimizing for both will use brain and look at the buff section.
Whether or not to use AP/bane and whether to default to the power template for random builds like grieving weaver is a bit ?? but I don't think any of those actually affect results, so, should be w/e.
> Chore: update buff presets

- src/components/sections/results/AppliedModifiers.jsx
- src/state/optimizer/optimizerCore.js
I actually think it's probably better to export the entire appliedModifiers data set out of the optimizer core so we can have full access to whatever data we'd like for rich formatting, but exporting utility functions out of the core works for now.
This styling is hot garbage :D
> Feat: Show amounts in appliedmodifiers

- src/components/baseComponents/Presets.jsx
- src/components/sections/buffs/BuffsSection.jsx
- src/components/sections/distribution/DistributionSection.jsx
- src/components/sections/extras/ExtrasSection.jsx
- src/components/sections/infusions/InfusionsSection.jsx
- src/components/sections/priorities/PrioritiesSection.jsx
- src/components/sections/traits/TraitsSection.jsx
This fixes up the MUI autocomplete component used for presets when there are a lot of them. It changes the onSelect callback to an onChange callback to fix its inconsistency firing the update, changes the <Preset> callback API to do this more cleanly, and also fixes the problem where when you switch professions or templates, the old text was still in the autocomplete, a mismatch compared to the actual state.
> Fix autocomplete

- src/components/sections/Affixes.jsx
- src/components/sections/forcedslots/ForcedSlots.jsx
- src/utils/gw2-data.js
Uses affixes data directly from gw2-data.js instead of having a separate copy in Affixes.jsx  and changes the affixes in the UI to `Startcase`.
> Move affixes data

- src/state/optimizer/optimizerCore.js
This allows forced slots to be affixes that aren't selected for optimization. (The code basically supported this already; the only thing preventing it from working was left over from the legacy optimizer.)
> Allow any forced slots

- src/components/sections/infusions/Infusions.jsx
Yep, I'm PRing my own PR.
Cute QoL improvement on the AR box that adds a dropdown with presets but otherwise continues to act as a text box using the `freeSolo` mode of MUI's `Autocomplete` component.
> Use <Autocomplete> for AR

- .editorconfig
- .gitattributes
unify end of line configuration among git, editorconfig and prettier (which detects .editorconfig so no need to specify in .prettierrc) to all use lf
without the unification inconsistency may occur with different user configurations of git and the default behavior of editorconfig and prettier 
best to run `git reset --hard` (remember to first stash uncommited changes, if any) or something alike to update indexes on local repositories after applying this change
> en of line unification

- src/components/sections/distribution/DamageDistribution.jsx
- src/state/optimizer/optimizerCore.js
Previously, backspacing out the contents of a distribution text box would silently leave the old values selected. Additionally, distribution numbers were inconsistently passed as strings instead of numbers, messing up some core logic (hashtag things that would not happen if we used typescript :P)
> Fix: Parse distribution inputs correctly 

- package.json
- src/components/gw2/Armor.jsx
- src/components/gw2/BackAndTrinkets.jsx
- src/components/gw2/Character.jsx
- src/components/gw2/Weapons.jsx
- yarn.lock
~Every gw2-ui component should be memoized imo, but if that's true, that should be added to gw2-ui, not this codebase.
However, this codebase currently passes arrays as props into `Item`s without memoizing the array generation, which would break the default React.memo implementation. I assume this will get refactored out at some point, but I'm not working on that rn, so this just puts a deep equality check on them.
Also memoized the GatsbyImage.
> memoize Item and GatsbyImage in character

- src/components/sections/distribution/DamageDistribution.jsx
- src/components/sections/infusions/InfusionHelper.jsx
- src/components/sections/infusions/Infusions.jsx
- src/components/sections/priorities/Priorities.jsx
- src/components/sections/results/TemplateHelper.jsx
- src/components/sections/traits/TraitAmount.jsx
- src/state/optimizer/optimizerCore.js
- src/state/optimizer/sagas.js
- src/state/slices/infusions.js
- src/utils/usefulFunctions.js
This makes the parseAmount function into a framework that can be used to create functions to parse any "please type a number" style text boxes in a consistent way and visually validate the text box input, and uses it for as many as I could find.
This should hopefully prevent any possible "invalid text results in stale input" bugs or "empty text box crashes the optimizer" bugs in the future.
I didn't use currying and partial application to create the derived functions from `parseNumber`, because I'm not brave enough (and also I think it would be hard to maintain if future contributors are not familiar with functional programming).
> Parse and validate text boxes consistently

- src/assets/modifierdata/buffs.yaml
- src/components/baseComponents/AmountInput.jsx
- src/components/sections/buffs/Buffs.jsx
- src/components/sections/results/AppliedModifiers.jsx
- src/components/sections/traits/Traits.jsx
- src/state/slices/buffs.js
This uses the same amount system for buffs as is used for traits and moves the AmountInput component into te baseComponents folder so I can reuse it later for confusion/torment more easily.
> Standardize amounts

- src/state/createStore.js
I'm sure there's a better way to do this... you know, preferably automatically.
This adds a key we can manually bump to invalidate the persisted gw2-ui cache for game patches.
> Feat: Add (manual) cache invalidation to gw2-ui cache

- src/components/sections/results/ResultTable.jsx
- src/components/sections/results/ResultTableHeaderRow.jsx
Changes the leftmost table header cell to healing or survivability when that's the selected sort mode.
Am I using useTranslation correctly?
> Fix: change table header when rankBy changes

- gatsby-node.js
The configuration `resolve.modules: [path.resolve('./node_modules')]` is a potentially harmful. It will make webpack module resolution behave differently from what node/npm/yarn does.        
In particular, the result of `path.resolve('./node_modules')` is an **absolute path**. According to [webpack configuration document](https://webpack.js.org/configuration/resolve/#resolvemodules), this will make webpack **only** search for dependencies in the **root** `node_modules` directory instead of in the **nested** `node_modules` directories first. However sometimes nested dependencies have version confliction which is why there may be nested `node_modules` directories (to allow different versions of packages to exist) in the first place. Forcing webpack to only search in the root `node_modules` …
> fix webpack resolve configuration

- src/components/sections/controls/CopyTemplateButton.jsx
This adds a bit of indentation to the template exports used for the main site so they can be pasted into the CMS and look clean.
> indent template exports

- .eslintrc.json
- package.json
- src/components/sections/distribution/DamageDistribution.jsx
- src/state/slices/distribution.js
- yarn.lock
This PR removes the noUI-slider dependency and instead makes use of the mui ones. One minor issue that arises is that the legacy slider is less pretty now due to it being impossible to color parts between sliders. I think thats acceptable in exchange for consistent styling and one less dependency we need to worry about. 
Please properly check my changes to the legacy (old) slider! I did test it but I'm not entirely sure the conversions I did are correct.
> refactor: remove noui-slider dependency

- package.json
ExtractLocale appears to have been broken, presumably by the move to Gatsby v4 or something related to it.
I don't understand what exactly this does and so I don't see why it would work, but it seems to? Also, the script seems to work slightly differently now?
> Fix: extractLocale broken

- package.json
- src/assets/modifierdata/testModifiers.js
Node 16's `--experimental-json-modules` option now requires `assert { type: 'json' }` after a JSON module import, but as this is experimental syntax still, this breaks ESLint unless we install a Babel plugin. Rather than bothering with this, I just used `fs.readFile` and `JSON.parse` to load the JSON. Too bad. Babel will support it eventually, I'm sure.
> Fix test scripts for newer Node 16 version

- src/assets/modifierdata/metadata.js
- src/assets/modifierdata/testModifiers.js
- src/state/optimizer/optimizerCore.js
This code is an absolute damn nightmare. But... 
```yaml
conversionAfterBuffs:
Bleeding Coefficient: {Critical Chance: 2400%}
```
...should now work to simulate sharper images on power chronomancer (`4.8 hits per second * 5 seconds per stack * 100% chance of triggering on critical hit = 2400%`), and
```yaml
attributes:
Power Coefficient: [17.26, converted]
Bleeding Coefficient: [2.4, converted]
```
...should now work to simulate a geomancy sigil triggered off cooldown (in both weapon sets, or one if you're on a revenant) (`0.25 power coefficient * 690.5 weapon strength / 10 second interval` power; `3 stacks * 8 seconds / 10 second interval` bleeding), and...
```yaml
attributes:
Flat DPS: [150, converted]
```
...should work to simulate lifesteal food (I've heard numbers between 130 and …
> Feat: Backend for coefficient effects and on-crit traits

- src/assets/modifierdata/ranger.yaml
Added Expertise conversion of own 120 Vitality bonus for [Taste of Danger](https://wiki.guildwars2.com/wiki/Taste_for_Danger).
I noticed a discrepancy between ingame stats & the optimizer for Expertise on Condi Soulbeast.
Ingame (no Expertise from Food):
Optimizer (no Expertise from Food):
Seems like the game includes the 120 Vitality gained for the Expertise conversion, which is exactly 8 Expertise. Other conversions seem to be unaffected by the gained Vitality (tested with [Magnanimous Sharpening Stone](https://wiki.guildwars2.com/wiki/Magnanimous_Sharpening_Stone)).
> Fix Ranger Taste for Danger conversion

- src/assets/modifierdata/buffs.yaml
- src/assets/modifierdata/testModifiers.js
- src/components/sections/results/BuildShareModal/BuildShareModal.jsx
- src/components/url-state/schema/SchemaDicts.js
- src/components/url-state/schema/package.json
- src/state/optimizer/sagas.js
- src/state/slices/buildPage.js
- src/utils/package.json
This adds a schema entry for buffs like we have for the other keys and uses it for buff encode/decode (although it is not currently the same system using the compression library), so that we can append new buffs onto the end of the list and old links will continue to work.
It adds a check to testModifiers that checks the schemas (not all of them unfortunately) to make sure we don't forget to update the schema when new modifier data is added, including buffs.
I had to add a dummy `package.json` to `src/components/url-state/schema/` to get node to import the schema in module mode; hopefully that doesn't break anything.
> Fix: Use schema for assumedbuffs

- src/components/GearOptimizer.jsx
- src/components/sections/controls/Controls.jsx
- src/components/sections/results/BuildShareModal/BuildShareModal.jsx
- src/components/sections/results/BuildShareModal/ModalContent.jsx
- src/components/sections/results/BuildShareModal/SkillSelect.jsx
- src/components/sections/results/BuildShareModal/generateLink.js
- src/components/sections/results/ResultDetails.jsx
- src/components/sections/results/TemplateHelperSections.jsx
- src/components/sections/results/table/ResultTable.jsx
- src/components/sections/sharing/SharingSection.jsx
this pr shall rework the share logic. Multiple actions are being taken: 
- move all share buttons to a centralized section below the result table 
- provide clear instructions on how to use it
- add an option to copy builds instead of opening in new tab 
- extract the link generation logic 
TODO:
> feat: rework share logic a bit

- plugins/gatsby-plugin-top-layout/TopLayout.js
- src/components/sections/results/table/ResultTable.jsx
- src/components/sections/results/table/ResultTableHeaderRow.jsx
- src/utils/placeholder-unused-theme.jsx
yikes
not sure what we want to do about this - some of the styles on the optimizer table are shared with the (completely different) tables in the main site, but most aren't. I think it would make sense to have an object of the shared theme keys with no table overrides at all, then export a mainSiteTheme and an optimizerTheme object (or whatever) with the table keys separate for each; that way there doesn't have to be any overrides.
> Attempt to fix mobile table

- src/assets/modifierdata/food.yaml
- src/assets/modifierdata/metadata.js
- src/assets/modifierdata/testModifiers.js
- src/assets/presetdata/preset-extras.yaml
- src/components/url-state/schema/SchemaDicts.js
- src/state/optimizer/optimizerCore.js
- src/state/slices/extras.js
Fully support all-damage modifiers like those on renegade buffing the lifesteal effect.
I may actually wind up doing this differently, as some of the possibilities for dual sigils involve having a more integrated way to have separate effects in one extra selection. Works for now, though.
The default 4.3 proc/10sec frequency (2.33s interval) for these is fairly arbitrary, but it's what I used for earth sigil and it's reasonably within the range of a couple benchmarks done with lifesteal food, idk.
> Feat: Lifesteal food

- locales/en/translation.json
- src/components/url-state/URLStateExport.jsx
This skips using the link shortener in staging/preview/local development builds, to prevent people sharing short links that redirect to an invalid location.
> Feat: Disable URL shortener in preview

- src/components/sections/distribution/DamageDistribution.jsx
- src/components/sections/distribution/DistributionSection.jsx
- src/state/slices/distribution.js
Percent distribution, as well as being weird enough that I doubt anyone ever used it (the hypothetical inputs were impossible to obtain without a spreadsheet, and if you had one, it would be a lot more more work than outputting coefficients), also outputs meaningless damage numbers instead of DPS and is incompatible with all of the new modifier types like earth sigil.
I left the meaningless `version` and `values1` keys in the state at the moment so as not to merge conflict with whatever work Kulinda has done on the core.
> Chore: Remove percent distribution

- cleanupLocale.js
- package.json
This creates a script that strips the beginning of the e.g. `affix_whatever` autogenerated values in the en locale file.
It's vanilla CJS because apparently using esm or typescript to write and run a (generously) 8 line script in 2022 without 45 characters of boilerplate is still fucking impossible.
~~PR since the package.json merge conflict will be easier to fix this way if we merge 437 - will wait for a decision on that.~~ actually whatever I can just merge
> Chore: create cleanupLocale script

- .github/workflows/previews-cf.yml
This allows you to write the command described in the description of a PR to disable cloudflare preview creation for any pushes to it.
~~Here is a test:~~
I have now removed the test.
> Chore: Implement [no previews] PR body command

- src/components/baseComponents/BackgroundImage.jsx
- src/components/baseComponents/Layout.jsx
- src/components/nav/NavBar.jsx
- src/pages/index/index.jsx
This:
- Changes the behavior of the responsive <Layout> component to always return the same DOM structure, preventing a huge freeze when you resize the window past the 1200px boundary as the entire React tree gets rerendered. (could upstream to RDC?)
- Replaces our manual setResponsiveness implementation with an MUI useMediaQuery.
> Fix: responsive breakpoint performance/simplicity

- src/assets/modifierdata/mesmer.yaml
This fixes the Vitality to Ferocity conversion ratio in the Virtuoso Quiet Intensity trait. The conversion is 10% not 7%.
> Fix Virtuoso Quiet Intensity conversion

- src/assets/presetdata/preset-affixes.yaml
- src/assets/presetdata/templates.yaml
This splits the healing affix preset between fractal and raid mode so that it can be customized per-mode. Apparently this just works!
> Split heal priority preset between gamemodes

- src/assets/modifierdata/buffs.yaml
- src/assets/modifierdata/food.yaml
- src/assets/modifierdata/revenant.yaml
- src/assets/presetdata/preset-distribution.yaml
\o/
Notably since damage was multiplicative by default the only distribution to change is power vindicator (thankfully)
I also assume that the default stat conversion of "buff" means only converted in very specific cases/not converted and that when someone like beng says a trait's bonus is converted that maps to the same as our "converted". This is at least the impression I got from the source code but would like to confirm
> Revenant modifier updates courtesy of beng!

- src/assets/modifierdata/revenant.yaml
Hi, realized about the new split in Roiling Mists in a past patch now that we were trying to optimize a revenant build. 
Will probably open a new PR later if I spot any other WvW modifier that is not up to date.
Thank you!
> Update WvW Roiling Mists

- src/assets/presetdata/preset-distribution.yaml
- src/assets/presetdata/preset-traits.yaml
Available in EI's json under statsAll -> boonAvg for the next time I start looking at the individual boon graph and counting stability sections.
> Correctly set Alac tempest's average boon number

- locales/en/translation.json
- src/assets/modifierdata/elementalist.yaml
- src/assets/modifierdata/engineer.yaml
- src/assets/modifierdata/necromancer.yaml
- src/assets/modifierdata/ranger.yaml
- src/assets/modifierdata/revenant.yaml
- src/assets/modifierdata/thief.yaml
- src/assets/modifierdata/warrior.yaml
- src/pages/index/index.jsx
https://wiki.guildwars2.com/wiki/Game_updates/2023-06-27
Not too happy with the big block of herald facet passives, ideas for improvement welcome
10% all damage needs uptime
10% -> 13% power to conc conversion in pve only
0.5% -> 0.25% in pve only
Increased the minimum damage bonus from 5% to 10% and increased
the maximum damage bonus from 10% to 15% in PvE only.
Gain power, gain additional power when wielding a sword
120, 120, pet also gains it
10% strike damage with uptime
Grants condition damage when equipped and while wielding a cepter
90, +90, 7% condi convert to healing power
Reduced the damage increase against high-health foes from 25% to
7% and the damage increase vs. foes with barrier from 50% to 10%
in WvW only.
Increased the base precision-to-ferocity conversion to 10%. This …
> June 27: Update traits and skills

- src/assets/modifierdata/elementalist.yaml
- src/assets/modifierdata/engineer.yaml
- src/assets/modifierdata/mesmer.yaml
- src/assets/modifierdata/revenant.yaml
- src/assets/modifierdata/testModifiers.js
As far as we know, every outgoing condition damage modifier in the game has been additive.
This adds a check to testModifiers enforcing this rule, which we should remove if at any point a multiplicative outgoing condition damage modifier is discovered.
Slightly messes up the power catalyst template, but like, whatever. Every template is dead anyway, making this a good time.
Resolves #522.
> Data: set every unconfirmed +outgoing cdmg mod to add

- locales/en/translation.json
- src/pages/index/index.jsx
I'm likely to be busy Tuesday/Wednesday so my original plan of "just update the few traits they're reworking" is out the window.
Expected trait changes with numbers impact are Scourge and Specter but one of the Specter changes is missing a number
> Add disclaimer for July 18th patch

- src/state/optimizer-parallel/calculate.ts
Reuses already-instantiated workers when running more than one calculation in Rust mode. Should fix the "if I press calculate a few times I run out of memory" problem.
> Fix: Reuse workers

- src/state/sagas/buildPageSaga.js
Without making a new build page schema, this ensures that the build page will not crash.
Revert this commit in #597.
> Fix: Temporarily fix build page crash

- src/assets/modifierdata/revenant.yaml
https://wiki.guildwars2.com/wiki/Burst_of_Strength
Doesn't mark any templates as out of date since all templates are baseline out of date.
I'm planning on starting back on the template data entry after the balance patch on the 26th (though I might be driven to do things before then out of boredom, like #588 would be pretty cool)
> Add Burst of Strength's PvE condi mod; Split out WvW Burst of Strength

- locales/en/translation.json
- src/components/nav/NavBar.jsx
This is a more straightforwards solution that avoids potential issues with translation context extraction.
See also https://github.com/discretize/discretize-gear-optimizer/pull/600#issuecomment-1736332418
> Replace buildTemplateOutdated and context with outdated

- functions/share/create.ts
- functions/share/load.ts
- tsconfig.json
As per https://developers.cloudflare.com/pages/platform/functions/typescript/, this types the Cloudflare functions using the `PagesFunction` type.
`yarn run tsc` is still not happy.
> Chore: type functions

- src/assets/modifierdata/mesmer.yaml
- src/assets/modifierdata/warrior.yaml
- src/assets/testData.js
Superiority Complex and Pure Strike are traits with critical damage bonuses that additively increase under certain conditions. We implement these bonuses as a second, separate trait bonus entry, which in theory should be additive with the first bonus, but not with a different critical damage bonus.
In practice, there are only two of these traits and they cannot be simultaneously enabled, as they are on different classes. Thus, simply marking these as additive should give accurate results.
Instead, though, to ensure that it is impossible to run into accuracy issues at a later date (e.g. if we do more testing and determine that some critical damage bonuses actually are additive with each other), this PR implements the bonus values as multiplicative using arithmetic, as suggested by REMagic …
> Implement increased critical damage traits as mult

- .github/workflows/previews-cf.yml
- .github/workflows/staging-cf.yml
I know of no way to test this besides merging it and then deploying some dummy content, so... fingers on the revert button I guess.
This attempts to switch from Cloudflare's hosted build integration to performing a build inside a Github Action and uploading the result via https://github.com/cloudflare/pages-action.
See: https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration/
> Use cloudflare direct deployment

- package.json
- yarn.lock
As far as I know, this dependency field is not needed and just causes a lot of pollution of the Yarn global cache. Let's see if it's true.
> Chore: Remove `wasm_module` dependency

- src/state/optimizer/optimizerCore.ts
- wasm_module/src/optimizer_core.rs
We don't use `convertafterbuffs` on any of these attributes (after the previous fix to reinforced armor), so this actually does nothing, but this fixes them not being applied in those cases.
> Fix: `convertafterbuffs` on precision/ferocity/concentration/vitality

- wasm_module/rust-toolchain
The rust-toolchain file is apparently supposed to be toml now: https://blog.rust-lang.org/2020/11/27/Rustup-1.23.0.html#new-format-for-rust-toolchain
I know nothing about this ecosystem; should this also use the `components` or the `targets` field?
> Update rust-toolchain file

- locales/en/translation.json
- src/assets/modifierdata/elementalist.yaml
- src/assets/modifierdata/engineer.yaml
- src/assets/modifierdata/guardian.yaml
- src/assets/modifierdata/mesmer.yaml
- src/assets/modifierdata/necromancer.yaml
- src/assets/modifierdata/ranger.yaml
- src/assets/modifierdata/revenant.yaml
- src/assets/modifierdata/warrior.yaml
- src/assets/presetdata/preset-traits.yaml
Also some very persnickety renames for consistency
Of note are the removal of stats on Heat the Soul and Eternal Champion, causing the removal of both trait's modifier data. Next, there's the movement of the healing modifier from Banshee's Wail to Life from Death, a minor fix for the heal scourge template
> Modifier updates (mostly wvw splits)

- functions/share/create.ts
- package.json
- pnpm-lock.yaml
As well-described in [Sindre Sorhus' post here](https://sindresorhus.com/blog/goodbye-nodejs-buffer), node's `buffer` is basically just a weird `Uint8Array`. We're using some dependencies in the short link generation cloudflare function that expect `buffer`s and also aren't typed. This uses the `uint8array-extras` package instead.
> Chore: Migrate from `buffer` to `Uint8Array`

- src/components/sections/results/TemplateHelper.jsx
The template-from-log tool tries to subtract lifesteal effects, but it doesn't do it automatically since it's not totally accurate. This is an additional manual step and it's more often than not correct, so I figure I may as well enable it by default; in the case where people double check their result they'll catch anything wrong either way and in the case where they don't this is more likely to be correct. Also yay less busywork.
@hobinjk pinging for visibility!
[no previews]
> Feat: Default to subtracting lifesteal in template creation tool

- package.json
- pnpm-lock.yaml
- src/components/sections/results/table/ResultTable.jsx
- src/components/sections/results/table/ResultTableRow.jsx
- src/state/optimizer-parallel/calculate.ts
- src/state/optimizer/optimizer.ts
- src/state/optimizer/optimizerCore.ts
- src/state/optimizer/worker.ts
- src/state/sagas/calculationSaga.ts
- src/state/slices/controlsSlice.ts
- src/state/slices/extras.ts
- src/vite-env.d.ts
- vite.config.js
There's a longstanding annoyance where optimizer browser tabs that weren't currently visible onscreen would be throttled by the browser to calculate at tiny fractions of full speed. Browsers only do this when you run expensive math on the main rendering thread, which you aren't supposed to do (I had put a lot of work into carefully doing it so it wouldn't freeze the page, but still).
This enables full-speed background calculation by moving the "regular" mode's calculation to a worker thread where it should be using vite-plugin-comlink, and removes some hard-to-read code that was used to mitigate the performance impact of not having done that.
This is also a slight performance gain, as rendering UI updates doesn't interrupt calculation anymore, but it was already optimized fairly well so …
> Feat: Faster calc when in background; improve perf

- package.json
- pnpm-lock.yaml
- vite.config.js
Enables source map creation in production, allowing console output to link to real code instead of obfuscated code. This project is open source anyway, so there's really no reason not to.
Due to the linked bug, this causes a bunch of (seemingly harmless) error messages during build. The workaround included works fine but I have no idea what it does; don't love that.
[draft previews]
> Feat: Enable source maps

- src/state/optimizer/optimizerCore.ts
- wasm_module/src/optimizer_core.rs
Changes the storage and display of "critical damage" values to include +outgoing critical damage modifiers.
Resolves #479.
Notably, this will result in character data generated for the main discretize site before and and after this change to have different critical damage values in some cases. This change is technically a further departure from the ingame hero panel... but in most cases it didn't match anyway, due to things like averaging out fencer's finesse stacks.
[no previews]
> Feat Save and show critical damage including mods

- .husky/pre-commit
- .lintstagedrc.js
- docs/Contributing/Readme.md
- package.json
- pnpm-lock.yaml
Installs an optional pre-commit hook that will lint and format staged files and test YAML data before committing. Git hooks are something I've wanted to look into for a while and this was mostly an excuse to do it.
I don't want all contributors to have to deal with them—they're slow, and if we get less-experienced contributors whose useful contributions don't pass the linter I'm happy to deal with that in the PR rather than have them be unable to commit. This therefore declines to add `"prepare": "husky"` as a package script and puts the enable instructions in the readme.
General annoyances:
- `eslint` throws warnings when `lint-staged` feeds it a file in its ignore list unless you use the `--no-warn-ignored` flag, which isn't supported until you upgrade to flat config, which not every …
> Feat: Create optional pre-commit lint/test hook

- src/assets/modifierdata/food.yaml
- src/assets/modifierdata/relics.yaml
- src/assets/modifierdata/runes.yaml
- src/assets/modifierdata/sigils.yaml
- src/assets/modifierdata/utility.yaml
- src/components/sections/extras/ExtraSelection.jsx
- src/components/sections/extras/ModalContent.jsx
- src/components/sections/results/table/ResultTableRow.jsx
Currently we display things like "two sigils" using one of the sigils, which is kind of fine where we can override the text next to the icon, but can be confusing in the results table where there is no text and the non-overridden tooltip is the only thing visible (noticeable in #775).
I finally bothered to look at the gw2-ui `<Item />` API to (kind of) fix this and override the tooltips too.
This would be better as a simple property on `<Item />` letting the user override the tooltip with arbitrary text, or more preferably the generic "'blank sigil/rune' components using https://wiki.guildwars2.com/wiki/User:Soulblydd/Images" that I've wanted forever, but this will do for now.
[no previews]
> Feat: Override extras tooltips when overriding names

- src/state/optimizer-parallel/modes/normal.ts
- src/state/optimizer-parallel/worker/workerMessageTypes.ts
- wasm_module/src/optimizer_core.rs
Currently, during a multicore Rust mode calculation, the Rust module sends its list of Combination objects back to the main thread with each progress update, and `enhanceResults` is called using the rust-serialized Combination object. This, notably, isn't the same thing that happens when the final results are calculated, which simply references the Combination objects that have been on the Javascript side the whole time. The progress-mode code here causes the result character display to crash, since the Rust-side version of the Combination object excludes some data and we don't properly fix it in `enhanceResults`.
This PR removes the Rust-to-JS serialization and uses the same always-javascript Combination objects to run `enhanceResults` in progress mode as in finish mode.
Note that …
> Fix: Crash when selecting result during multicore calculation

- src/components/nav/NavSettings.jsx
- src/components/sections/controls/Controls.jsx
- src/pages/index/index.jsx
- src/state/optimizer-parallel/calculate.ts
This implements the stop calculation button, but not the resume button, in the multicore rust mode.
It stops the calculation by terminating the active workers from the main thread and creating new ones. This obviously isn't as elegant as having the Rust code actually pause and let handlers run to check if it's received a message every so often (probably doable with `wasm_bindgen_futures` or whatever), but I don't know how to do that and this is at least better than having to refresh the page and lose your whole state.
> Feat: Implement stop button in multicore mode

- wasm_module/src/lib.rs
- wasm_module/src/optimizer_core.rs
Baby's first nontrivial Rust code; yes I will get around to learning the language for real some time, no today is not that day. Not AI-assisted—I hate using AI for code in its current state—but I was copy-pasting out of docs examples, so it arguably may as well be.
Anyway: this, for compatibility with #796, ensures that `character.combination_id` will refer to the index of the relevant combination relative to the entire combination list, not to the list picked by heuristics, by using `picked_combination_ids` as a whitelist instead of filtering the array with it beforehand.
Resolves #798.
> Fix: Inconsistent combination ids in heuristics mode

- src/assets/presetdata/metadata.ts
- src/assets/presetdata/preset-affixes.yaml
- src/assets/presetdata/preset-buffs.yaml
- src/assets/presetdata/preset-distribution.yaml
- src/assets/presetdata/preset-extras.yaml
- src/assets/presetdata/preset-traits.yaml
- src/assets/presetdata/templateTransform.ts
- src/assets/testData.js
- src/components/sections/affixes/AffixesSection.tsx
- src/components/sections/buffs/BuffsSection.tsx
- src/components/sections/distribution/DistributionSection.tsx
- src/components/sections/extras/ExtrasSection.tsx
- src/components/sections/traits/TraitsSection.tsx
- src/state/slices/buffs.ts
- src/state/slices/controlsSlice.ts
- src/state/slices/distribution.ts
- src/state/slices/extras.ts
- src/state/slices/priorities.ts
- src/state/slices/skills.ts
- src/state/slices/traits.ts
Fun fact: YAML is a superset of JSON, so pasting JSON into YAML is totally a thing you can do without defining it as a string and parsing it. Not sure how I had forgotten about this fact, honestly.
> refactor: Convert preset data to YAML; improve typecheck

- locales/en/translation.json
- src/components/nav/NavSettings.tsx
- src/pages/index/index.jsx
- src/state/optimizer-parallel/calculate.ts
- src/state/optimizer/detectFirefox.ts
- src/state/optimizer/optimizer.ts
- src/state/optimizer/optimizerCore.ts
- src/state/optimizer/worker.ts
- src/state/sagas/calculationSaga.ts
- src/state/slices/controlsSlice.ts
Enables multithreading in the regular (javascript) mode.
This is, in certain circumstances, as fast as (or even slightly faster than) the Rust/Webassembly mode. Not all the time, though. Notably, thread counts more than four or five in javascript mode show no additional speedup in Firefox, even when adjusting browser flags; I'm not currently sure why this is but it seems to have to do with memory allocation issues. Chrome/Edge/Safari (and the Rust/Webassembly mode in Firefox) don't suffer from this.
> feat: Utilize multiple CPU cores in all modes

- docs/Contributing/Data Format/Modifiers.md
- src/assets/testData.js
- src/components/sections/results/ResultCharacter.jsx
Implements a long-requested toggle to simulate character attributes when out of combat, so users can compare the ingame hero panel to the optimizer's. This is not, and cannot, be perfect (at least without more user input UI). Is a soulbeast player equipping an axe? A torch or dagger? Both? Neither? There's no way to know or assume in a way that would be consistent for every build.
On a best-effort basis, this assumes that an elementalist is in fire attunement (not air) and a power guardian or warrior isn't on their greatsword set; these are kind of arbitrary and the UI warning shouldn't commit to us keeping those kinds of things true as it's quite hard.
I don't know how to integrate this into the UI; not a big fan of what's committed here at all. Maybe an implementation within the …
> Feat: Simulate unbuffed hero panel attributes

- src/state/async/calculationThunks.ts
- src/state/optimizer/optimizer.ts
- src/state/optimizer/optimizerCore.ts
Each time the worker threads communicate results back to the main thread, they currently include the `settings` object on every character in the list of (up to) 50 character results, even though those settings will be the same for every result from a certain combination.
Back when the calculation was not run in a worker, this just meant that every character object had a pointer to the same settings object. But data sent via postMessage is cloned, meaning that every character object includes its own fresh copy of the identical settings object once it's sent back from a worker thread.
This moves the "attach settings object" behavior out of optimizercore, which is definitely run in a worker thread, and into optimizer.ts (the coordinator that manages state between workers and sorts results), …
> refactor: Avoid sending settings from worker threads

- package.json
- pnpm-lock.yaml
Dependabot won't do this automatically, as vite-plugin-wasm's peer dependency range doesn't include v6.
Per https://vite.dev/guide/migration.html#migration-from-v5, it seems like no changes are needed for v6.
> chore(deps): bump vite from 5.4.11 to 6.0.1

- build/main.jsx
- package.json
- pnpm-lock.yaml
- src/pages/build/index.jsx
- src/pages/index/main.jsx
- src/utils/globals/index.ts
- src/utils/globals/styles/Layout.jsx
- src/utils/globals/styles/globals.js
- src/utils/globals/styles/muiTheme.jsx
As mentioned in https://github.com/discretize/discretize-ui/pull/57, the `@discretize/globals` package doesn't need to be shared, and legacy code in it and in its tooling is getting in the way of Typescript and React updates. This includes the referenced files in this repo and removes the dependency.
> chore(deps): Remove @discretize/globals dependency

- wasm_module/.cargo/config
- wasm_module/Cargo.lock
- wasm_module/Cargo.toml
- wasm_module/src/utils.rs
See https://rust-random.github.io/book/update-0.9.html (not really used; I just followed the deprecation messages in-IDE) and https://github.com/rust-random/getrandom?tab=readme-ov-file#webassembly-support
> chore(deps): Update rand to 0.9 and getrandom to 0.3

- .github/workflows/build-deploy.yml
- .github/workflows/build-with-image.yml
- .github/workflows/previews-cf.yml
`cloudflare/pages-action` appears to be abandoned (without a note in the readme! I am not impressed by the state of your tooling, cloudflare!), so I think we'll eventually have to do this. `cloudflare/wrangler-action` currently does not create github deployments, to my knowledge, however, so I'm happy to wait.
See https://github.com/cloudflare/pages-action/issues/117 and https://github.com/cloudflare/wrangler-action/issues/274.
[draft previews]
> chore: Use `cloudflare/wrangler-action` in deploy

- src/components/sections/results/ResultDetails.tsx
- src/components/sections/results/TemplateHelperSections.jsx
- src/utils/assumedBuffs.ts
Resolves #884.
This only applies to the results section at the bottom of the main optimizer page; the build page has a bunch of missing/inaccurate buffs, omnipotion being only one of them.
[no previews]
> fix: Omnipotion always appearing in results

- docs/Contributing/Data Format/Modifiers.md
- locales/en/translation.json
- src/assets/modifierdata/buffs.yaml
- src/assets/modifierdata/metadata.ts
- src/assets/testData.js
- src/components/sections/buffs/Buffs.jsx
- src/components/url-state/schema/SchemaDicts.js
- src/state/slices/buffs.ts
- src/utils/assumedBuffs.ts
Implements frost aura as a buff. This required some plumbing since we didn't have "aura" as an option to render a buff.
Annoyingly, our gw2-ui library displays this as "Frost" with no way to override the text. I can implement the override, but I'm not going to do it now.
> feat: Implement frost aura buff

- src/components/sections/results/TemplateHelper.jsx
Arc now differentiates between the weapon type of each Clone, leading to names like Axe Clone instead of just Clone. Fix clone detection for this new naming scheme.
> Fix template helper's detection of Clone damage

- src/components/sections/results/TemplateHelper.jsx
When using the template helper to load data from a log URL, this:
- automatically and unconditionally moves the phantasm+clone damage to the "power2" box, if present
- makes a set of buttons appear if there are non-phantasm-or-clone minions that include/don't include them in the "power" box, defaulting to "don't include" (as it's more obvious something should be changed if the wrong setting is selected that way)
> Improve template helper phantasm/minion loading

- .editorconfig
- package.json
- pnpm-lock.yaml
- src/assets/modifierdata/elementalist.yaml
- src/assets/modifierdata/engineer.yaml
- src/assets/modifierdata/guardian.yaml
- src/assets/modifierdata/mesmer.yaml
- src/assets/modifierdata/necromancer.yaml
- src/assets/modifierdata/ranger.yaml
- src/assets/modifierdata/revenant.yaml
- src/assets/modifierdata/thief.yaml
- src/assets/modifierdata/warrior.yaml
- src/components/url-state/schema/SchemaDicts.js
- src/utils/gw2-data.ts
- src/utils/mapping/specializations.json
VoE specs can be selected, but they currently don't have profession images in the character component (@gw2princeps I don't suppose you want to get some more made?), and builds with them will currently not have icons in the dropdown selector (must be pushed in a gw2-ui update).
> feat: Implement visions of eternity spec selection
